"""empty message

Revision ID: 65f9009a4c0a
Revises: 69f85e325a25
Create Date: 2023-11-03 16:38:47.727085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65f9009a4c0a'
down_revision = '69f85e325a25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.alter_column('params',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=512),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.alter_column('params',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###
