"""empty message

Revision ID: 69f85e325a25
Revises: 8069bdc8dd16
Create Date: 2023-11-03 14:50:04.710527

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69f85e325a25'
down_revision = '8069bdc8dd16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repeat_traceid', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('old_resp', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('new_resp', sa.Text(), nullable=True))
        batch_op.alter_column('path',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('params',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.alter_column('params',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('path',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('new_resp')
        batch_op.drop_column('old_resp')
        batch_op.drop_column('repeat_traceid')

    # ### end Alembic commands ###
