"""empty message

Revision ID: 8069bdc8dd16
Revises: 
Create Date: 2023-11-02 17:39:30.418456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8069bdc8dd16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=100), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=True),
    sa.Column('params', sa.String(length=100), nullable=True),
    sa.Column('hash', sa.String(length=32), nullable=True),
    sa.Column('first_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('result', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    # ### end Alembic commands ###
