"""empty message

Revision ID: 9350d40376ab
Revises: ab4c55cf2231
Create Date: 2023-11-13 12:02:30.656239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9350d40376ab'
down_revision = 'ab4c55cf2231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.drop_column('old_traceid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_traceid', mysql.VARCHAR(length=64), nullable=True))

    # ### end Alembic commands ###
