"""empty message

Revision ID: c86ef7cbd1c1
Revises: 65f9009a4c0a
Create Date: 2023-11-03 17:21:52.139031

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c86ef7cbd1c1'
down_revision = '65f9009a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.alter_column('params',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.alter_column('params',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=True)

    # ### end Alembic commands ###
